controller_manager:
  ros__parameters:
    # Adjusted to the Webots step time (32ms) 1s/0.032.
    update_rate: 32 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rosbot_base_controller:
      type: diff_drive_controller/DiffDriveController

rosbot_base_controller:
  ros__parameters:
    left_wheel_names: ["fl_wheel_joint", "rl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "rr_wheel_joint"]

    wheel_separation: 0.186
    wheel_radius: 0.043
    wheel_separation_multiplier: 1.45

    use_stamped_vel: false
    enable_odom_tf: false