controller_manager:
  ros__parameters:
    update_rate: 31 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    rosbot_base_controller:
      type: diff_drive_controller/DiffDriveController

rosbot_base_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.186
    wheel_radius: 0.0425
    # wheel_separation_multiplier: 1.45

    use_stamped_vel: false
    enable_odom_tf: false